"""KDS 24 (교량설계기준, 한계상태설계법) 모듈.

KDS 14 가 강도설계법이라면 KDS 24 는 한계상태설계법이다. 두 기준은 같은
역학을 쓰지만 **안전율을 거는 자리가 다르다** — KDS 14 는 공칭강도에
강도감소계수를 한 번 곱하고, KDS 24 는 재료마다 재료계수를 곱해 설계
재료강도를 만든다.

구현 범위

- ``materials`` — 재료계수(표 1.4-1), 설계 재료강도, 단면설계용 응력-변형률
  (KDS 24 14 21 1.4, 3.1)
- ``design_code`` — :class:`KDS24` 설계기준 클래스, 극한한계상태 휨·축력
  (KDS 24 14 21 4.1.1)
- ``loads`` — 하중조합과 하중수정계수 (KDS 24 12 11 4.1, KDS 24 10 11 1.3)
- ``live_load`` — 차량활하중 KL-510, 충격, 다차로 재하 (KDS 24 12 21 4.3, 4.4)
- ``shear`` — 변각 트러스 모델 전단 (KDS 24 14 21 4.1.2)
- ``serviceability`` — 응력 한계·균열폭·처짐·피로 (KDS 24 14 21 4.2, 4.3)

두 기준의 대응은 문서의 [KDS 14 와 KDS 24 비교] 를 참고한다.
"""

from __future__ import annotations

from . import live_load, loads, serviceability, shear
from .design_code import (
    KDS24,
    biaxial_exponent,
    minimum_eccentricity,
)
from .live_load import (
    FATIGUE_TRUCK_RATIO,
    IMPACT_PERCENT,
    IMPACT_PERCENT_FATIGUE,
    LANE_LOAD_BASE,
    TRUCK_AXLE_LOADS,
    TRUCK_AXLE_POSITIONS,
    TRUCK_TOTAL_LOAD,
    LiveLoadEffect,
    adtt_single_lane,
    fatigue_truck_moment,
    girder_live_load,
    impact_buried,
    impact_factor,
    lane_load,
    lane_moment,
    lane_shear,
    lane_width,
    multiple_presence,
    number_of_lanes,
    truck_lane_fraction,
    truck_moment,
    truck_shear,
)
from .loads import (
    BRIDGE_GRADE_FACTORS,
    COMBINATIONS_BY_NAME,
    LOAD_COMBINATIONS,
    LOAD_SYMBOLS,
    PERMANENT_LOAD_FACTORS,
    LoadCombination,
    bridge_grade_factor,
    evaluate_all,
    governing_combination,
    load_modifier,
    permanent_load_factor,
)
from .materials import (
    ALPHA_CC,
    ES,
    MATERIAL_FACTORS,
    PHI_C_ULS,
    PHI_S_ULS,
    characteristic_tensile_strength,
    concrete_curve_table,
    curve_parameters,
    design_compressive_strength,
    design_profile,
    design_stress,
    design_tensile_strength,
    design_yield_strength,
    elastic_modulus,
    equivalent_block,
    material_factors,
    mean_compressive_strength,
    mean_tensile_strength,
)
from .serviceability import (
    COUPLER_FATIGUE_STRENGTH,
    DESIGN_GRADES,
    EXPOSURE_MINIMUM_GRADE,
    MAX_BAR_DIAMETER,
    MAX_BAR_SPACING,
    CrackWidthCheck,
    DesignGrade,
    concrete_stress_limit,
    coupler_fatigue_strength,
    crack_spacing,
    crack_spacing_unreinforced,
    crack_width,
    deflection_limit,
    effective_tension_depth,
    fatigue_check_required,
    fatigue_stress_range_limit,
    max_bar_diameter,
    max_bar_spacing,
    minimum_crack_reinforcement,
    minimum_design_grade,
    nonuniform_stress_factor,
    steel_stress_limit,
    strain_difference,
    stress_distribution_factor,
    tendon_stress_limit,
    web_effective_tensile_strength,
)
from .shear import (
    COT_THETA_MAX,
    COT_THETA_MIN,
    ShearCheck,
    alpha_cw,
    axial_stress,
    check_shear,
    concrete_shear_strength,
    design_concrete_shear_strength,
    kappa,
    max_shear_strength,
    maximum_shear_reinforcement,
    maximum_stirrup_spacing,
    minimum_concrete_shear_strength,
    minimum_shear_reinforcement_ratio,
    nu,
    required_stirrup_spacing,
    shear_reinforcement_strength,
    uncracked_shear_strength,
)

__all__ = [
    "ALPHA_CC",
    "BRIDGE_GRADE_FACTORS",
    "COMBINATIONS_BY_NAME",
    "COT_THETA_MAX",
    "COT_THETA_MIN",
    "COUPLER_FATIGUE_STRENGTH",
    "CrackWidthCheck",
    "DESIGN_GRADES",
    "DesignGrade",
    "ES",
    "EXPOSURE_MINIMUM_GRADE",
    "FATIGUE_TRUCK_RATIO",
    "IMPACT_PERCENT",
    "IMPACT_PERCENT_FATIGUE",
    "KDS24",
    "LANE_LOAD_BASE",
    "LOAD_COMBINATIONS",
    "LOAD_SYMBOLS",
    "LiveLoadEffect",
    "LoadCombination",
    "MATERIAL_FACTORS",
    "MAX_BAR_DIAMETER",
    "MAX_BAR_SPACING",
    "PERMANENT_LOAD_FACTORS",
    "PHI_C_ULS",
    "PHI_S_ULS",
    "ShearCheck",
    "TRUCK_AXLE_LOADS",
    "TRUCK_AXLE_POSITIONS",
    "TRUCK_TOTAL_LOAD",
    "adtt_single_lane",
    "alpha_cw",
    "axial_stress",
    "biaxial_exponent",
    "bridge_grade_factor",
    "characteristic_tensile_strength",
    "check_shear",
    "concrete_curve_table",
    "concrete_shear_strength",
    "concrete_stress_limit",
    "coupler_fatigue_strength",
    "crack_spacing",
    "crack_spacing_unreinforced",
    "crack_width",
    "curve_parameters",
    "deflection_limit",
    "design_compressive_strength",
    "design_concrete_shear_strength",
    "design_profile",
    "design_stress",
    "design_tensile_strength",
    "design_yield_strength",
    "effective_tension_depth",
    "elastic_modulus",
    "equivalent_block",
    "evaluate_all",
    "fatigue_check_required",
    "fatigue_stress_range_limit",
    "fatigue_truck_moment",
    "girder_live_load",
    "governing_combination",
    "impact_buried",
    "impact_factor",
    "kappa",
    "lane_load",
    "lane_moment",
    "lane_shear",
    "lane_width",
    "live_load",
    "load_modifier",
    "loads",
    "material_factors",
    "max_bar_diameter",
    "max_bar_spacing",
    "max_shear_strength",
    "maximum_shear_reinforcement",
    "maximum_stirrup_spacing",
    "mean_compressive_strength",
    "mean_tensile_strength",
    "minimum_concrete_shear_strength",
    "minimum_crack_reinforcement",
    "minimum_design_grade",
    "minimum_eccentricity",
    "minimum_shear_reinforcement_ratio",
    "multiple_presence",
    "nonuniform_stress_factor",
    "nu",
    "number_of_lanes",
    "permanent_load_factor",
    "required_stirrup_spacing",
    "serviceability",
    "shear",
    "shear_reinforcement_strength",
    "steel_stress_limit",
    "strain_difference",
    "stress_distribution_factor",
    "tendon_stress_limit",
    "truck_lane_fraction",
    "truck_moment",
    "truck_shear",
    "uncracked_shear_strength",
    "web_effective_tensile_strength",
]
